# Operaciones con filas y columnas

Crea un programa llamado MatrizSecuencia.py que defina una matriz de 3 filas y 3 columnas con los números del 0 al 8.

In [1]:
import numpy as np

matriz = np.arange(0, 9).reshape((3, 3))

Imprime el resultado por pantalla.

In [2]:
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
